### ISSUE TITLE
[EVENT] Jupyter Hack Night

### ISSUE THREAD

**Issue by marimeireles** [PyLadiesBerlin/community-organisation#10]
Hi all,
Tracking our organization of the Hack Night event here on  GH.

The event is mainly being organized by @discombobulateme.
The current idea is to have a hybrid event so @willingc would be able to join us online.
@hbcarlos and I would be present IRL in Berlin.

The event lasts 2h we'd need all the mentors to be available during this time.
It'd be nice to select a few beginners bugs in Jupyter related repositories to prepare ourselves. A good first bug is a bug that has a clear outline of what has to be done, the public for this event might vary in experience but it's always difficult to acclimatize yourself to a new project, so I guess it's good if the issues are thoroughly explained.

I was thinking we could have issues both in the main Jupyter repo and also in the expanded universe (widgets, xeus kernels, etc). Let me know if you have any different ideas for this event, happy to hear them and incorporate them.

@discombobulateme can you please give us an idea of the times that would work for our current event venues?

Cheers everyone, thanks for offering to help!

**Comment by marimeireles** [comment]
pinging @discombobulateme here :)
My calendar is pretty much free for a month from now (21.05 further). Also a few days in april but I think that might be too short notice.
Should we try to schedule it for next month from now? That will give us time to create some good first issues or just separate them.

**Comment by hbcarlos** [comment]
> Should we try to schedule it for next month from now? That will give us time to create some good first issues or just separate them.

Sounds good! Keep in mind that JupyterCon is on May 10-12. I won't be available that week.

**Comment by discombobulateme** [comment]
Will give you options :)

- [ ] May 2, Tue
- [ ] May 3, Wed
- [ ] May 4, Thu
- [ ] May 16, Tue
- [ ] May 17, Wed
- [ ] May 18, Thu

**Comment by marimeireles** [comment]
Sorry, I'm only back in berlin after the 21.05 :(

**Comment by discombobulateme** [comment]
- [ ] May 23 Tue
- [ ] May 24 Wed
- [ ] May 25 Thu

:)

**Comment by hbcarlos** [comment]
I prefer May 25, but the other two options also work for me.

**Comment by marimeireles** [comment]
I have a meeting at 20h... on the 25th
Could also be in the weekend? Or on the 23rd for me.

**Comment by discombobulateme** [comment]
I avoid working on weekends o_O for my sanity. Shall we settle on the 23rd, then? 19-22h?

**Comment by marimeireles** [comment]
Makes sense!
Alright :) seems good to me

**Comment by discombobulateme** [comment]
Room is booked!
I'll start the Meetup page, you can edit :)

**Comment by hbcarlos** [comment]
Great! Thanks @discombobulateme!

**Comment by discombobulateme** [comment]
- [x] Room booked
- [x] Draft event: https://www.meetup.com/pyladies-berlin/events/293122125/ @hbcarlos if you give me your email I can add you as a co-organizer :) if you prefer not, follow the text in the following comment

**Comment by marimeireles** [comment]
hey all
@anapaulagomes reached out to me on twitter, she's a super capable software engineer doing lots of cool things with data.
Ana, Carlos and I used to work in the same company doing several different jupyter stuff. I mainly worked with kernels, I guess Carlos did more widgets work but by now he must have worked with all kinds of stuff :)
Let us know if you have any questions and would like to join us as a facilitator
@discombobulateme (Paloma) is organizing everything and she is fabulous!

**Comment by discombobulateme** [comment]
@marimeireles & @hbcarlos just waiting for your 👍 to publish the event 😎

**Comment by anapaulagomes** [comment]
Hi folks! How can I help? :)

**Comment by hbcarlos** [comment]
Hi @discombobulateme. Sorry for the delay. I'm swamped these days.

First, thanks for setting up the workshop and writing down the description.

Regarding the requirements, I would also add having conda/mamba installed, at least as optional. Every Jupyter subproject has install instructions for Conda, and I think it is better to use Conda environments.

> Any other requirements question
> 
> Bring your own laptop
> Have Github account: https://github.com/
> Have git installed: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

Have miniconda or micromamba installed (recommendable): 
  - miniconda: https://docs.conda.io/en/latest/miniconda.html
  - micromamba: https://mamba.readthedocs.io/en/latest/installation.html#manual-installation

On the other side, is the workshop focused on contributing to pandas? Just asking because pandas is not part of the Jupyter project, and I don't have experience with that library.

**Comment by discombobulateme** [comment]
hahahaha I used the pandas workshop as blue print 😅
good catch! will update with the requirements :D

**Comment by hbcarlos** [comment]
> I used the pandas workshop as blue print 

haha Nice! For a moment, I thought I was in the wrong workshop or something. hahaha

**Comment by hbcarlos** [comment]
Regarding the workshop, I would do a small intro to the Jupyter project (explaining what subproject we have). Then each participant can choose if they want to create an extension for jupyterlab, create their own Jupyter widget or contribute to one of the projects by tackling one of the "good first issues" from JupyterLab or Jupyter Widgets.

Some of the subprojects we can look into during the workshop and ways to collaborate:
* JupyterLab:
    * Documentation: https://jupyterlab.readthedocs.io/en/stable/getting_started/overview.html
    * "Good first issue": https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
    * Extension examples: https://github.com/jupyterlab/extension-examples
    * Template to create an extension: https://github.com/jupyterlab/extension-cookiecutter-ts
* Jupyter Widgets:
    * Documentation: https://ipywidgets.readthedocs.io/en/stable/
    * "Good first issue": https://github.com/jupyter-widgets/ipywidgets/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
    * Template to create a widget: https://github.com/jupyter-widgets/widget-ts-cookiecutter
* Kernels: (I'll leave this to @marimeireles )
* Accessibility:
    Isabela Presedo-Floyd leads this subproject and, in my opinion, is the most petite, friendly, and welcoming of all the subprojects. Most of them are amazing UI/UX designers trying to improve the accessibility in Jupyter front-ends (Lab, Notebook, and Hub). Still, they often lack front-end developers to apply their ideas. I don't have much experience in accessibility, but I can help with the technical part and introduce people to the subproject.
    * Documentation: https://jupyter-accessibility.readthedocs.io/en/latest/
    * Accessibility issues in JupyterLab: https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3Atag%3AAccessibility

**Comment by hbcarlos** [comment]
> Hi folks! How can I help? :)

Hi, @anapaulagomes! Welcome!

Do you have any experience with Jupyter?

**Comment by anapaulagomes** [comment]
Hey @hbcarlos! I have basic experience with Jupyter, and more with Python. None with TypeScript, though.

**Comment by hbcarlos** [comment]
Thanks, @anapaulagomes. In the Jupyter stack, all the backend components are built in Python, so your skills will be helpful during "office hours".

Jupyter-Server (the backend for JupyterLab and Jupyter Notebook) is written in Python. Most JupyterLab extensions come with a server extension in the same package to extend the server functionality, for example, by adding new endpoints.

We also use Python in Jupyter-Widgets. Widgets have two parts: a Python instance in the Kernel and a JavaScript instance in the front end (Notebook). It is possible to create cool widgets with basic JavaScript, and it is not necessary to use TypeScript.

If you have some spare time, you could look at the documentation and play around with it (feel free to ping me anytime for questions). It will be helpful to have more people with some knowledge.

If you prefer to help organize the event, you should talk to @marimeireles or @discombobulateme :)

**Comment by discombobulateme** [comment]
Ahhhh it will be a pleasure to see @anapaulagomes again! Are you back in Berlin?
@hbcarlos will you be with us in Berlin or remote? We want to try out a hybrid even, right? Will you or @marimeireles have some presentation/ first steps in the beginning?

**Comment by marimeireles** [comment]
I intend to give an introduction about xeus and the widgets ecosystem. What are they and high level outlook on how they work.
I can also check for the actual jupyter widgets repo to see if there are issues there I could help people to get done with.

**Comment by hbcarlos** [comment]
> will you be with us in Berlin or remote?

I'll be there with you. I'm also in Berlin.

> Will you or @marimeireles have some presentation/ first steps in the beginning?

Yes, we should give a brief introduction. I'm happy to talk about the ecosystem and how each piece interconnects.

**Comment by hbcarlos** [comment]
@marimeireles How do you want to orientate the workshop? Do you want to go for the "good first issues"? They are meant for new contributors with a low technical level. In addition, I just checked, and we have that label on every repository so people can choose where to contribute.

**Comment by marimeireles** [comment]
Hey @hbcarlos, do you wanna define what which one of us will talk about so we don't do duplicated work?
Or you think we can just complement each other on the parts we overlap?

**Comment by hbcarlos** [comment]
We should coordinate a bit. Are you going to JupyterCon? Maybe we can take some time during JupyterCon to meet and prepare a small presentation.

**Comment by hbcarlos** [comment]
Maybe we should also coordinate with @willingc.

**Comment by anapaulagomes** [comment]
More than happy to help during office hours, @hbcarlos! :) I'll take a look at the docs.

@discombobulateme yes, I am in Berlin! Glad to see you too! 😍

**Comment by discombobulateme** [comment]
Event published :) https://www.meetup.com/pyladies-berlin/events/293122125/?utm_medium=referral&utm_campaign=announceModal_savedevents_share_modal&utm_source=link

**Comment by anapaulagomes** [comment]
Folks, in the [query](https://github.com/search?q=is%3Aissue+is%3Aopen+is%3Asprint-friendly+user%3Ajupyter&type=Issues&ref=searchresults) shared in the developer contributing guide there are just a few issues and that don’t see beginners friendly. Do we have a plan B for it? Like, shall we focus on something else like developing a new widget or so?

**Comment by hbcarlos** [comment]
Hi, @anapaulagomes. There are beginners friendly issues:
* Jupyter Widgets: https://github.com/jupyter-widgets/ipywidgets/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
* IPyKernel: ???
* Jupyter Server: https://github.com/jupyter-server/jupyter_server/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22
* JupyterLab: https://github.com/jupyterlab/jupyterlab/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

You need to go to the repo you want to contribute and filter the issues with the tag `good first issue`.

**Comment by anapaulagomes** [comment]
Thanks @hbcarlos! I’ve only checked if this label existed for the main repo (jupyter/jupyter) and since it wasn’t there I assumed that it wasn’t used 😳

**Comment by marimeireles** [comment]
Besides I want to add some new ones in the extended universe of jupyter (the widgets and kernels) i’m on vacation rn but coming back next week!-mariana meirelesSent from phoneOn 18. May 2023, at 23:19, Ana Paula Gomes ***@***.***> wrote:﻿
Thanks @hbcarlos! I’ve only checked if this label existed for the main repo (jupyter/jupyter) and since it wasn’t there I assumed that it wasn’t used 😳

**Comment by marimeireles** [comment]
Yo frens
Happy we made this far!!

So I'm working on a small [slide deck ](https://docs.google.com/presentation/d/1BUtW6j0U82sV0po6QiqaySmNz9NqKswQbEniKvRWljA/edit?usp=sharing) it's not ready yet, hopefully it will be by tomorrow. Introducing high level concepts on how kernel and widgets work cause that's what I'll be tackling => essentially xeus stuff + ipycytoscape, Carlos. I can also grab some other widgets by QS but my actual proficiency lies in these two repos.

Today and tomorrow I intend to tag some extra good first issues and also take a look at the ipywidgets repo and see what I can do around there...

Excited to see yall tomorrow! LMK if you'd like me to change smth or do smth
Cheers!

**Comment by hbcarlos** [comment]
Thank you, @marimeireles! Your slides look great!

Your explanation of Kernels and Widgets looks excellent. I can not add anything there. I was thinking of preparing a small talk introducing Project Jupyter (governance, ways to contribute, etc.). I can also talk about the difference between the Classic Notebook, JupyterLab, and the new Notebook v7 (It is a huge change, and I think people will be interested in that).

@marimeireles Let me know what you think.

**Comment by marimeireles** [comment]
> Thank you, @marimeireles! Your slides look great!

Thanks! It's mostly taken from the docs 😈

> Your explanation of Kernels and Widgets looks excellent. I can not add anything there. I was thinking of preparing a small talk introducing Project Jupyter (governance, ways to contribute, etc.). I can also talk about the difference between the Classic Notebook, JupyterLab, and the new Notebook v7 (It is a huge change, and I think people will be interested in that).

That'd be excellent I was planning on just saying hey, jupyter lab is diff from notebooks it's very unfortunate PR move and I have no idea why they did it, but personally I have no idea what's up with nb 7 or anything like that, maybe you start then! Talking about governance and stuff.

Cheers!

@anapaulagomes no biggie :) thanks for coming!

**Comment by hbcarlos** [comment]
Thanks, @marimeireles.

To introduce myself, you can say that I'm a Scientific software developer at QuantStack, where I spend my time trying to improve the Jupyter ecosystem by working on JupyterLab-related projects.

**Comment by hbcarlos** [comment]
https://docs.google.com/presentation/d/1h2wMTKKvwb_DyAmDkGGOgJlReavEW_RwU7Xb0P6g5nw/edit#slide=id.g1e33cb3e4a9_0_713

**Comment by discombobulateme** [comment]
THANK YOU all for putting so much together and sharing with our lovely community <3 uffff its so hard to gather this knowledge and condense into a few minutes o_O 

As we were trying the hybrid version, the presentation part was recorded. I added to our PyLadies channel in case you would like to use it somewhere :)  https://youtu.be/_p609mR_8HU

**Comment by sleepypioneer** [comment]
Are you ok with me calling this issue done? @marimeireles @discombobulateme

**Comment by marimeireles** [comment]
Closing this as done
yaaay
thank you people
it was a pleasure :)
