### ISSUE TITLE
[EVENT] July 11th - Members Talk evening @ Plan D

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/community-organisation#12]
**Head organizer:** Jessica
**Co organizer:** Fan
**Slides/Moderation:**
**Speaker support:**

**Location:** Plan D
**Speaker:** Tamara
**Talk:** Modeling mental hops from one word to the next with NLP and Python
**Speaker:** Raana
**Talk:** How to be a good reviewer: Be honest, nice and a bad ass

## MONTH BEFORE
- [x] Define Speakers
- [x] Send Speakers guidelines email
- [x] Announce event with speakers, location, gender policy, photo policy on meetup page
- [x] Define hosts & collect host information
- [x] Send Host guidelines email
- [x] Organise Food/ drinks
- [x] Tweet event when announced
- [x] Check with speaker if coaches are needed and search for coaches

## TWO WEEKS BEFORE
- [x] Retweet event
- [x] Check with speaker about installation instructions/reading material and update announcement
- [x] Update meetup announcement with agenda, networking breaks, if snacks or drinks will be available
- [x] Check-in with hosts and ask if support is needed for reception

## WEEK BEFORE
- [x] Remind attendees to install requirements with comment and/or message on meetup
- [x] Send coaches the workshop/relevant material
- [x] Dry run with speaker

## WEEK OF THE EVENT
- [x] Tweet after event
- [x] Ask host if attendees list is needed and/or special location directions
- [x] Double check with host: microphone (if needed), soft drinks, power plugs, internet
- [x] Send to host to print [PyLadies arrow signs](https://docs.google.com/presentation/d/1_SNnpaWBK3I74e4TWW4wudf6JMGBSYaq_90W2BiCiEk/edit?usp=sharing)
- [x] Print [feedback forms]([feedback forms](https://docs.google.com/document/d/1jxBpZGpVUFIPMiQhG9O9_c2zi5LHFjhsR0dyCO2dAD4/edit?usp=sharing))
- [x] Prepare introduction slides past example

## DAY OF THE EVENT 
*(arrive 30-60 minute before event starts)*
- [x] Check projector, microphone, table setup, power extensions, recording if available
- [x] Support speaker(s) to test equipment
- [x] Stick PyLadies signs to guide attendees the location
- [x] Hang up or put out print outs with the WIFI (or find a similar solution)
- [x] Manage reception, give name tags if available
- [x] During the COVID 19 pandemic (and perhaps later) there might be additional health checks such as vaccination status or proof of a recent test to allow entry

## DURING THE EVENT
- [x] Do introduction and Community announcements
- [x] Take photos of all the speakers and audience
- [x] Tweet about it (or after the event with photos)

## AFTER THE EVENT
- [x] Tweet after event (if not done during the event)
- [ ] Upload photos to [google drive](https://drive.google.com/drive/folders/1hqNE_Ol8l8dqERk-PZ2xdODWV2Go7wLs?usp=sharing) (you need to be part of the google group to access this)
- [ ] Open PR with resources to this [repository](https://github.com/PyLadiesBerlin/resources)
- [ ] Email sponsors & host to thank them
- [x] Copy feedback forms to [feedback spreadsheet](https://docs.google.com/spreadsheets/d/1gk6tJ30WyG8tz7j5-V-SvHdR-C_TGyHLYkdjdlh_T14/edit?usp=sharing)
- [ ] Adjust guides if valuable feedback came up

**Comment by sleepypioneer** [comment]
Speaker will fill in the form when she has the information, I have emailed Plan D from our hosting list to see if they can host :)

**Comment by sleepypioneer** [comment]
@Gigi1111 FYI as they put you as a contact :) Let me know if you want to collaborate on this one!

**Comment by Gigi1111** [comment]
sure, I'd love to

**Comment by marimeireles** [comment]
happy to take on some of these, specially the non-social media related ones :)

**Comment by sleepypioneer** [comment]
@marimeireles how about prepping the slides? Are you also interested in doing speaker support (ie listening through a dry run and giving feedback?)
