### ISSUE TITLE
[EVENT] 1 August - Contributing to scikit-learn hack night @ DB Digital Campus

### ISSUE THREAD

**Issue by marenwestermann** [PyLadiesBerlin/community-organisation#18]
**Head organizer:** Maren
**Support organizer:** Salma, Edi, Bita
**Slides/Moderation:** Maren, Adrin, Guillaume
**Mentor support:** Maren

**Location:** DB Digital Campus, Event Café, Kynaststraße 1, Berlin

## MONTH BEFORE
- [x] Define Mentors
- [x] Announce event with mentors, location, gender policy, photo policy on meetup page
- [x] Define hosts & collect host information
- [x] Send Host guidelines email
- [x] Organise Food/ drinks
- [x] Tweet event when announced

## TWO WEEKS BEFORE
- [x] Retweet event
- [x] Check with mentors about installation instructions/reading material and a list of (beginner friendly) issues to work on
- [x] Update meetup announcement with agenda, networking breaks, if snacks or drinks will be available
- [x] Check-in with hosts and ask if support is needed for reception

## WEEK BEFORE
- [x] Remind attendees to install requirements with comment and/or message on meetup
- [x] Send coaches the workshop/relevant material

## WEEK OF THE EVENT
- [x] Ask host if attendees list is needed and/or special location directions
- [ ] Double check with host: microphone (if needed), soft drinks, power plugs, internet, tables and chairs
- [ ] Send to host to print [PyLadies arrow signs](https://docs.google.com/presentation/d/1_SNnpaWBK3I74e4TWW4wudf6JMGBSYaq_90W2BiCiEk/edit?usp=sharing)
- [x] Print [feedback forms]([feedback forms](https://docs.google.com/document/d/1jxBpZGpVUFIPMiQhG9O9_c2zi5LHFjhsR0dyCO2dAD4/edit?usp=sharing))
- [x] Prepare introduction slides past example

## DAY OF THE EVENT 
*(arrive 30-60 minute before event starts)*
- [x] Bring swag (stickers, T-shirts, other promotion material)
- [ ] Check projector, microphone, table setup, power extensions, recording if available
- [ ] Support mentor(s) to test equipment
- [ ] Stick PyLadies signs to guide attendees the location
- [ ] Hang up or put out print outs with the WIFI (or find a similar solution)
- [ ] Manage reception, give name tags if available
- [x] During the COVID 19 pandemic (and perhaps later) there might be additional health checks such as vaccination status or proof of a recent test to allow entry

## DURING THE EVENT
- [ ] Do introduction and Community announcements
- [ ] Take photos of all the speakers and audience
- [ ] Tweet about it (or after the event with photos)

## AFTER THE EVENT
- [ ] Tweet after event (if not done during the event)
- [ ] Upload photos to [google drive](https://drive.google.com/drive/folders/1hqNE_Ol8l8dqERk-PZ2xdODWV2Go7wLs?usp=sharing) (you need to be part of the google group to access this)
- [ ] Open PR with resources to this [repository](https://github.com/PyLadiesBerlin/resources)
- [ ] Email sponsors & host to thank them
- [ ] Copy feedback forms to [feedback spreadsheet](https://docs.google.com/spreadsheets/d/1gk6tJ30WyG8tz7j5-V-SvHdR-C_TGyHLYkdjdlh_T14/edit?usp=sharing)
- [ ] Adjust guides if valuable feedback came up

**Comment by sleepypioneer** [comment]
@marenwestermann can this issue now be closed?

**Comment by marenwestermann** [comment]
@sleepypioneer yes, thank you. Closing this now.
