### ISSUE TITLE
Get More Stickers

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/community-organisation#23]
We have 150$ from NODES which we want to use for PyLadies Berlin stickers. (information is in our email)

Previously we have used [StickerMule](https://www.stickermule.com/de)

Other options are [FlyerAlarm](https://www.flyeralarm.com/de/) (open-source diversity stickers are from there) and [awesome merchandise](https://www.awesomemerchandise.com/) (recommended by Tereza)

Attaching logos we used before for stickers - more file types can be found in https://drive.google.com/drive/u/2/folders/1dV2Ezol4Ikf3J2a1TtZ8hfrLrhl2rOY5

![pylady_geek_rainbow (1)](https://github.com/PyLadiesBerlin/community-organisation/assets/23617373/f6d588e2-ce34-4758-a454-aa32135bc3c3)
![pyladies_sticker_one](https://github.com/PyLadiesBerlin/community-organisation/assets/23617373/d74e58c0-001e-4977-a5e3-bb7f5e217947)

![pyladies_turm_logo07_d](https://github.com/PyLadiesBerlin/community-organisation/assets/23617373/3533924e-f82f-4d94-88de-c5350250f2ab)

**Comment by marenwestermann** [comment]
All stickers have arrived 🎉
