### ISSUE TITLE
[EVENT] September 12th - Preptember Hacktoberbest With Board Games @saucelabs

### ISSUE THREAD

**Issue by tiaversa** [PyLadiesBerlin/community-organisation#30]
**Head organizer:** @discombobulateme @tiaversa 
**Support organizer:**
**Slides/Moderation:**
**Speaker support:**

**Location:** Sauce Labs c/o WeWork, Warschauer Pl. 11-13, 10245 Berlin
**Speaker:**
**Talk:**

## MONTH BEFORE
- [x] Announce event with speakers, location, gender policy, photo policy on meetup page https://www.meetup.com/pyladies-berlin/events/295882657/?isFirstPublish=true
- [ ] Define hosts & collect host information
- [ ] Send Host guidelines email
- [x] Organise Food/ drinks
- [x] Tweet event when announced
- [ ] Check with speaker if coaches are needed and search for coaches

## TWO WEEKS BEFORE
- [ ] Retweet event
- [ ] Check with speaker about installation instructions/reading material and update announcement
- [ ] Update meetup announcement with agenda, networking breaks, if snacks or drinks will be available
- [ ] Check-in with hosts and ask if support is needed for reception

## WEEK BEFORE
- [ ] Remind attendees to install requirements with comment and/or message on meetup
- [ ] Send coaches the workshop/relevant material
- [x] Dry run with speaker

## WEEK OF THE EVENT
- [x] Tweet after event
- [ ] Ask host if attendees list is needed and/or special location directions
- [ ] Double check with host: microphone (if needed), soft drinks, power plugs, internet
- [ ] Send to host to print [PyLadies arrow signs](https://docs.google.com/presentation/d/1_SNnpaWBK3I74e4TWW4wudf6JMGBSYaq_90W2BiCiEk/edit?usp=sharing)
- [ ] Print [feedback forms]([feedback forms](https://docs.google.com/document/d/1jxBpZGpVUFIPMiQhG9O9_c2zi5LHFjhsR0dyCO2dAD4/edit?usp=sharing))
- [x] Prepare introduction slides past example

## DAY OF THE EVENT 
*(arrive 30-60 minute before event starts)*
- [x] Check projector, microphone, table setup, power extensions, recording if available
- [ ] Support speaker(s) to test equipment
- [x] Stick PyLadies signs to guide attendees the location
- [ ] Hang up or put out print outs with the WIFI (or find a similar solution)
- [ ] Manage reception, give name tags if available
- [ ] During the COVID 19 pandemic (and perhaps later) there might be additional health checks such as vaccination status or proof of a recent test to allow entry

## DURING THE EVENT
- [x] Do introduction and [Community announcements ](https://docs.google.com/presentation/d/17mw0M7mU8FXTndAA_o8UBukWSe07wWruNcQV5KIWu6A/edit?usp=sharing)
- [x] Take photos of all the speakers and audience
- [x] Tweet about it (or after the event with photos)

## AFTER THE EVENT
- [ ] Tweet after event (if not done during the event)
- [ ] Upload photos to [google drive](https://drive.google.com/drive/folders/1hqNE_Ol8l8dqERk-PZ2xdODWV2Go7wLs?usp=sharing) (you need to be part of the google group to access this)
- [ ] Open PR with resources to this [repository](https://github.com/PyLadiesBerlin/resources)
- [ ] Email sponsors & host to thank them
- [ ] Copy feedback forms to [feedback spreadsheet](https://docs.google.com/spreadsheets/d/1gk6tJ30WyG8tz7j5-V-SvHdR-C_TGyHLYkdjdlh_T14/edit?usp=sharing)
- [ ] Adjust guides if valuable feedback came up

**Comment by discombobulateme** [comment]
Pic uploaded to the meetup event page and twitter ;)
