### ISSUE TITLE
PyLadies Tshirts

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/community-organisation#4]
Sauce Labs will sponsor us Tshirts, amount to be confirmed. Designs for consideration are below.

code
```
pyladies = ['for_all', 'diversity']
def in_pyladies(person):
    if all(value in person for value in pyladies):
        return 'Welcome'
    else:
        return 'read the code of conduct'
```

### Options

![Image](https://user-images.githubusercontent.com/23617373/227992554-f57f80af-2179-402a-9bf7-4e877a375171.png)
![Image](https://user-images.githubusercontent.com/23617373/227992556-440c132b-3656-4c3e-b017-2385d15d9c01.png)
![Image](https://user-images.githubusercontent.com/23617373/227992558-7cd8a7ae-8c57-4bfb-8672-14b0d9ce2190.png)
![Image](https://user-images.githubusercontent.com/23617373/227992555-8b282f36-5c74-44f6-aace-1e376fe30c83.png)
![Image](https://user-images.githubusercontent.com/23617373/227992557-f3ef41b6-364f-43f1-97c7-4f20bf4e09d6.png)

**Comment by sleepypioneer** [comment]
Currently we are running a vote to decide which design/colour we go with :)

**Comment by cmaureir** [comment]
I modified a bit the code to make valid

**Comment by sleepypioneer** [comment]
Awesome thanks I was copy pasting from slack. Depending on the outcome it might be worth checking @discombobulateme sees the alteration 😊

**Comment by sleepypioneer** [comment]
Should we call this done or keep it open for the Dask shirts we might still get?

**Comment by cmaureir** [comment]
I guess we can open another one for the Dask ones, to avoid using the same design and try a new one :D

**Comment by discombobulateme** [comment]
We have 100 tshirts delivered! 
Provider: Pit Schmeißner <pit@up42.de>
Textile: https://shop.continentalclothing.de/shop/style/0/1
Continental Clothing - UNISEX ORGANIC T-SHIRT - EP01

Color: mint green
XS - 5
S - 10
M - 40
L - 26
XXL - 5

Color: Ash Black (mint green was missing)
4 x L 
10 x XL

![IMG_4674](https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/d3c74779-af60-4bbd-a1d5-1374666d4073)
