### ISSUE TITLE
[EVENT] April 21st - PyLadies Berlin City Tour, starting @ The BCC

### ISSUE THREAD

**Issue by berlin-pyladies** [PyLadiesBerlin/community-organisation#42]
**Head organizers:** @discombobulateme @sleepypioneer 

**Location:** Start at the Reichstag

## MONTH BEFORE
- [x] create the google form
- [x] Tweet with google form
- [x] Mastodon with google form
- [x] LinkedIn with google form
- [x] Instagram with google form?
- [x] Send form to Alina

## WEEK OF THE EVENT
- [ ] Update folks via email on meeting point
- [ ] telegram group?

## DURING THE EVENT
- [ ] Take photos of all the speakers and audience
- [ ] Tweet about it (or after the event with photos)

## AFTER THE EVENT
- [ ] Tweet after event (if not done during the event)
- [ ] Upload photos to [google drive](https://drive.google.com/drive/folders/1hqNE_Ol8l8dqERk-PZ2xdODWV2Go7wLs?usp=sharing) (you need to be part of the google group to access this)

**Comment by sleepypioneer** [comment]
## spots to visit (order of suggested visit)

Fernsehenturm (Alexanderplatz): [map](https://maps.app.goo.gl/3kfmggnt4tAYNiKF8)

World time clock (Alexanderplatz): [map](https://maps.app.goo.gl/dbvajRgXtDnj5CR19)

Red townhall (Alexanderplatz): [map](https://maps.app.goo.gl/KYVEWgC2JSXrWr3n7)

Hackescher hof: [map](https://maps.app.goo.gl/KhRctBEfamSicBUU9_)

Musuem island: [map](https://maps.app.goo.gl/2mqoVdQWBtGg4ra47)

Fleamarket (art market): [map](https://maps.app.goo.gl/3iTGPBttKM8jR6Ud9)

< Suggestion 1 >

Fleamarket (regular flea market): [map](https://maps.app.goo.gl/FKzvqfWcGVQmm9W3A)

Walk along Spree riverwalk

Reichstag: [map](https://maps.app.goo.gl/mwHJhEWQfkFPkyiv6)

Brandenburger Tor: [map](https://maps.app.goo.gl/jWwBSCezHMJ1RYjLA)

< Suggestion 2 >

Walk along unter den linden

Babel Platz: [map](https://maps.app.goo.gl/16urzFkUxPF9ekbr5)

Brandenburger Tor: [map](https://maps.app.goo.gl/jWwBSCezHMJ1RYjLA)

Reichstag: [map](https://maps.app.goo.gl/mwHJhEWQfkFPkyiv6)

< Both suggestions then follow >

Jewish memorial: [map](https://maps.app.goo.gl/tNYpoc3a3rrTDxMY7)

DDR watch tower (postdammer platz): [map](https://www.google.de/maps/place/DDR-Wachturm/@52.5085353,13.3770982,17z/data=!3m1!4b1!4m6!3m5!1s0x47a851ce99f7ae91:0x87c8b6677d18734d!8m2!3d52.5085353!4d13.3796785!16s%2Fg%2F11b6dz2rss?entry=ttu)

Oldest traffic light in Germany (postdammer platz): [map](https://maps.app.goo.gl/L9kzhkioKq9CCjpD8)

Checkpoint charlie: [map](https://maps.app.goo.gl/NuqBxp1LBWgSrho89)

From here you could take the u6 back to Alexanderplatz



@discombobulateme let me know what you think, maybe we can plan in a trial walk to see how long this takes, I would already say this is a couple of hours, but as its very central folks could stop early if its too much, we can also plan breaks.

**Comment by discombobulateme** [comment]
This would be my suggestion considering that the Bundestag visitation would be the main activity (which would help us a lot as a "guide" to decompress after Humble Data and allow people to have tones of info about the city in advance still with sunshine (crossing fingers) 

Im thinking, as this is the one thing with schedule, we should meet and start there and have 1h30 to decompress and maybe eat something after Humble Data. It is far from the BCC (almost 4km) to walk there in a group would take a long time, but we could walk back and maybe have tea or a beer on the way back?

Meeting point: Bundestag 17h
It takes between 45m-1h
Walking tour
- Walk along Spree riverwalk (between the Bundestag buildings, its gorgeous there)
- Brandenburger Tor: [map](https://maps.app.goo.gl/jWwBSCezHMJ1RYjLA)
- Babel Platz: [map](https://maps.app.goo.gl/16urzFkUxPF9ekbr5)
- Musuem island: [map](https://maps.app.goo.gl/2mqoVdQWBtGg4ra47)
- Hackescher hof: [map](https://maps.app.goo.gl/KhRctBEfamSicBUU9_) we finish here having a dinner or a drink

Ufff That will go way over 19h but I think its a pretty good plan <3

**Comment by alina-lenhardt** [comment]
Hi, this is Alina from communications team at PyCon DE & PyData Berlin. Once you create a meetup event, could you please share a link with me? I'll add it on the conference website. Thanks!

**Comment by discombobulateme** [comment]
hi @alina-lenhardt this is th elink: https://forms.gle/Jucxpy5SzPZNKUas6 than you!

**Comment by discombobulateme** [comment]
Hey, I had an issue with the Bundestag website and though I had booked the tour, but didnt :'( soooo this is the new suggested tour, although a bit too long maybe... its the big plan, of course possible to shorten it. It will be a mix of landmarks and women connected to each place :) 

https://maps.app.goo.gl/11wZpyPwYwDKq7dj7

<img width="1711" alt="Screenshot 2024-04-15 at 10 07 29 PM" src="https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/e5172ee6-de74-441b-afc6-737890f04cca">

**Comment by berlin-pyladies** [comment]
Looks good, the map say 1:44 walking so I would think it's around 2.5 hours if you plan to talk at each point (might be a bit exhausting after the workshop but folks could always get public transport at different stops) I need to drop out around 6:45/7pm just FYI but can join until then :)

**Comment by discombobulateme** [comment]
This ended up being the[ final route](https://maps.app.goo.gl/DHEHx8Zx3Pu8NCsc8) (not able to do it all in 2h o_O), in case we would like to ever do it again 

<img width="1457" alt="Screenshot 2024-04-22 at 11 49 55 AM" src="https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/5729cc53-8a2b-46b3-9ad9-22ea2680d637">

![IMG_8468](https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/a1ad115b-8fc6-4bec-8ba1-29b54773a95a)
![IMG_8442](https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/3f08f676-781b-42c6-9c99-14d715e23992)
![IMG_8448](https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/fc8848b6-605f-4c12-8fae-a521cd424861)
![IMG_8464](https://github.com/PyLadiesBerlin/community-organisation/assets/7980624/b5165139-c300-4326-8104-836462c6899c)
