### ISSUE TITLE
[CONFERENCE] 22 - 24 April PyConDE & PyData Berlin PyLadies

### ISSUE THREAD

**Issue by marenwestermann** [PyLadiesBerlin/community-organisation#44]
**PyLadies contact:** @marenwestermann @discombobulateme @sleepypioneer 
**Conference contact:** Alexander Hendorf
**Conference website:** https://2024.pycon.de/
**Conference description:** Community conference
**Does the conference pass our acceptance criteria:** Yes

**Location:** Berlin Congress Center
**Date:** 22 - 24 April 2024
**PyLadies Attending:** PyLadies Germany chapters

## Agreement with Conference
ie what we receive as a community partner and the expectation on us.
**Tickets (number of free or discounted):** PyLadies Germany got 20 free tickets that were raffled
**Advertising we will offer (ie slack/ twitter/ event page):** Slack, LInkedIn, Mastodon, Twitter, Instagram
**Additional support (ie PyLadies stand/ lunch/ CFP support):** stand and maybe lunch

**Comment by marenwestermann** [comment]
### What we need for the booth:

- [ ] roll up (@marenwestermann)
- [ ] donation box (@marenwestermann)
- [ ] games (@discombobulateme @sleepypioneer)
- [ ] stickers (@marenwestermann has about 300; maybe get more)
- [ ] T-shirts (@discombobulateme @tiaversa @sleepypioneer)
- [ ] time table with shifts (@marenwestermann  to create and post on slack)
- [ ] print outs? 
- [ ] post about booth on slack and social media
- [ ] 
- [ ] to be continued (please update :) )

**Comment by berlin-pyladies** [comment]
Closing issue as conference is over, this was a great success 🎉  Thank you all!
